export interface CurrencyInfo {
  code: string;
  symbol: string;
  name: string;
  country: string;
}

export const WORLD_CURRENCIES: CurrencyInfo[] = [
  { code: 'USD', symbol: '$', name: 'US Dollar', country: 'United States' },
  { code: 'EUR', symbol: '€', name: 'Euro', country: 'Eurozone' },
  { code: 'GBP', symbol: '£', name: 'British Pound', country: 'United Kingdom' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen', country: 'Japan' },
  { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar', country: 'Canada' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', country: 'Australia' },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', country: 'Switzerland' },
  { code: 'CNY', symbol: 'CN¥', name: 'Chinese Yuan', country: 'China' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', country: 'India' },
  { code: 'PKR', symbol: 'Rs', name: 'Pakistani Rupee', country: 'Pakistan' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', country: 'Bangladesh' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', country: 'Brazil' },
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble', country: 'Russia' },
  { code: 'MXN', symbol: 'MX$', name: 'Mexican Peso', country: 'Mexico' },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand', country: 'South Africa' },
  { code: 'AED', symbol: 'AED', name: 'UAE Dirham', country: 'United Arab Emirates' },
  { code: 'SAR', symbol: 'SAR', name: 'Saudi Riyal', country: 'Saudi Arabia' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', country: 'Singapore' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', country: 'New Zealand' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', country: 'Hong Kong' },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', country: 'Sweden' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', country: 'Norway' },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone', country: 'Denmark' },
  { code: 'PLN', symbol: 'zł', name: 'Polish Zloty', country: 'Poland' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira', country: 'Turkey' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht', country: 'Thailand' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', country: 'Indonesia' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', country: 'Malaysia' },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso', country: 'Philippines' },
  { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', country: 'Vietnam' },
  { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound', country: 'Egypt' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', country: 'Nigeria' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', country: 'Kenya' },
  { code: 'ARS', symbol: 'AR$', name: 'Argentine Peso', country: 'Argentina' },
  { code: 'CLP', symbol: 'CLP$', name: 'Chilean Peso', country: 'Chile' },
  { code: 'COP', symbol: 'COP$', name: 'Colombian Peso', country: 'Colombia' },
  { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', country: 'Peru' },
  { code: 'ILS', symbol: '₪', name: 'Israeli New Shekel', country: 'Israel' },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won', country: 'South Korea' },
  { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar', country: 'Taiwan' },
  { code: 'MAD', symbol: 'MAD', name: 'Moroccan Dirham', country: 'Morocco' },
  { code: 'DZD', symbol: 'DZD', name: 'Algerian Dinar', country: 'Algeria' },
  { code: 'IQD', symbol: 'IQD', name: 'Iraqi Dinar', country: 'Iraq' },
  { code: 'QAR', symbol: 'QAR', name: 'Qatari Riyal', country: 'Qatar' },
  { code: 'KWD', symbol: 'KWD', name: 'Kuwaiti Dinar', country: 'Kuwait' },
  { code: 'OMR', symbol: 'OMR', name: 'Omani Rial', country: 'Oman' },
  { code: 'BHD', symbol: 'BHD', name: 'Bahraini Dinar', country: 'Bahrain' },
  { code: 'JOD', symbol: 'JOD', name: 'Jordanian Dinar', country: 'Jordan' },
  { code: 'LBP', symbol: 'L£', name: 'Lebanese Pound', country: 'Lebanon' },
  { code: 'GEL', symbol: '₾', name: 'Georgian Lari', country: 'Georgia' },
  { code: 'AMD', symbol: '֏', name: 'Armenian Dram', country: 'Armenia' },
  { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', country: 'Kazakhstan' },
  { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', country: 'Ukraine' },
  { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', country: 'Belarus' },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', country: 'Hungary' },
  { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', country: 'Czech Republic' },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu', country: 'Romania' },
  { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', country: 'Bulgaria' },
  { code: 'ISK', symbol: 'kr', name: 'Icelandic Krona', country: 'Iceland' },
  { code: 'RSD', symbol: 'din', name: 'Serbian Dinar', country: 'Serbia' },
  { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar', country: 'Fiji' },
  { code: 'MUR', symbol: 'Rs', name: 'Mauritian Rupee', country: 'Mauritius' },
  { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa', country: 'Maldives' },
  { code: 'NPR', symbol: 'Rs', name: 'Nepalese Rupee', country: 'Nepal' },
  { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', country: 'Sri Lanka' },
  { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', country: 'Myanmar' },
  { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', country: 'Cambodia' },
  { code: 'LAK', symbol: '₭', name: 'Lao Kip', country: 'Laos' },
  { code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik', country: 'Mongolia' },
  { code: 'AFN', symbol: '؋', name: 'Afghan Afghani', country: 'Afghanistan' },
  { code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni', country: 'Tajikistan' },
  { code: 'TMT', symbol: 'TMT', name: 'Turkmenistani Manat', country: 'Turkmenistan' },
  { code: 'UZS', symbol: 'soʻm', name: 'Uzbekistani Som', country: 'Uzbekistan' },
  { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', country: 'Ethiopia' },
  { code: 'GHS', symbol: 'GH₵', name: 'Ghanaian Cedi', country: 'Ghana' },
  { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', country: 'Tanzania' },
  { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', country: 'Uganda' },
  { code: 'RWF', symbol: 'FRw', name: 'Rwandan Franc', country: 'Rwanda' },
  { code: 'BWP', symbol: 'P', name: 'Botswana Pula', country: 'Botswana' },
  { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar', country: 'Namibia' },
  { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', country: 'Mozambique' },
  { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', country: 'Angola' },
  { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', country: 'Zambia' },
  { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', country: 'Dominican Republic' },
  { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', country: 'Costa Rica' },
  { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', country: 'Guatemala' },
  { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', country: 'Honduras' },
  { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', country: 'Nicaragua' },
  { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', country: 'Panama' },
  { code: 'PYG', symbol: '₲', name: 'Paraguayan Guaraní', country: 'Paraguay' },
  { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso', country: 'Uruguay' },
  { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano', country: 'Bolivia' },
  { code: 'VES', symbol: 'Bs.S', name: 'Venezuelan Bolívar', country: 'Venezuela' },
  { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar', country: 'Jamaica' },
  { code: 'BSD', symbol: 'B$', name: 'Bahamian Dollar', country: 'Bahamas' },
  { code: 'BBD', symbol: 'Bbd$', name: 'Barbadian Dollar', country: 'Barbados' },
  { code: 'TTD', symbol: 'TT$', name: 'Trinidad & Tobago Dollar', country: 'Trinidad and Tobago' },
  { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', country: 'East Caribbean' },
  { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', country: 'West Africa' },
  { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', country: 'Central Africa' },
  { code: 'BND', symbol: 'B$', name: 'Brunei Dollar', country: 'Brunei' },
  { code: 'KGS', symbol: 'сом', name: 'Kyrgyzstani Som', country: 'Kyrgyzstan' },
  { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', country: 'Azerbaijan' },
  { code: 'ALL', symbol: 'L', name: 'Albanian Lek', country: 'Albania' },
  { code: 'BAM', symbol: 'KM', name: 'Bosnian Convertible Mark', country: 'Bosnia & Herzegovina' },
  { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', country: 'North Macedonia' },
  { code: 'MDL', symbol: 'L', name: 'Moldovan Leu', country: 'Moldova' },
  { code: 'CVE', symbol: 'Esc', name: 'Cape Verdean Escudo', country: 'Cape Verde' },
  { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', country: 'Gambia' },
  { code: 'LSL', symbol: 'L', name: 'Lesotho Loti', country: 'Lesotho' },
  { code: 'SZL', symbol: 'E', name: 'Eswatini Lilangeni', country: 'Eswatini' },
  { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', country: 'Madagascar' },
  { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', country: 'Malawi' },
  { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', country: 'Djibouti' },
  { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa', country: 'Eritrea' },
  { code: 'SOS', symbol: 'Sh.So.', name: 'Somali Shilling', country: 'Somalia' },
  { code: 'SLE', symbol: 'Le', name: 'Sierra Leonean Leone', country: 'Sierra Leone' },
  { code: 'LRD', symbol: 'L$', name: 'Liberian Dollar', country: 'Liberia' },
  { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', country: 'Haiti' },
  { code: 'GYD', symbol: 'G$', name: 'Guyanese Dollar', country: 'Guyana' },
  { code: 'SRD', symbol: 'Sr$', name: 'Surinamese Dollar', country: 'Suriname' },
  { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar', country: 'Belize' },
  { code: 'CUP', symbol: '$MN', name: 'Cuban Peso', country: 'Cuba' },
  { code: 'AWG', symbol: 'Afl.', name: 'Aruban Florin', country: 'Aruba' },
  { code: 'ANG', symbol: 'NAƒ', name: 'Netherlands Antillean Guilder', country: 'Curaçao' },
  { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', country: 'Papua New Guinea' },
  { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar', country: 'Solomon Islands' },
  { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', country: 'Vanuatu' },
  { code: 'WST', symbol: 'WS$', name: 'Samoan Tala', country: 'Samoa' },
  { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', country: 'Tonga' },
  { code: 'KMF', symbol: 'CF', name: 'Comorian Franc', country: 'Comoros' },
  { code: 'STN', symbol: 'Db', name: 'São Tomé Dobra', country: 'São Tomé & Príncipe' },
  { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', country: 'Burundi' },
  { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', country: 'DR Congo' },
  { code: 'SSP', symbol: 'SSP', name: 'South Sudanese Pound', country: 'South Sudan' },
  { code: 'SYP', symbol: 'LS', name: 'Syrian Pound', country: 'Syria' },
  { code: 'YER', symbol: 'YR', name: 'Yemeni Rial', country: 'Yemen' },
  { code: 'SDG', symbol: 'SDG', name: 'Sudanese Pound', country: 'Sudan' },
  { code: 'LYD', symbol: 'LD', name: 'Libyan Dinar', country: 'Libya' },
  { code: 'TND', symbol: 'DT', name: 'Tunisian Dinar', country: 'Tunisia' },
  { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya', country: 'Mauritania' },
  { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', country: 'Guinea' },
  { code: 'GNF', symbol: 'FG', name: 'Bissau-Guinean Franc', country: 'Guinea-Bissau' },
];

const CURRENCY_MAP = new Map<string, CurrencyInfo>();
WORLD_CURRENCIES.forEach(c => CURRENCY_MAP.set(c.code, c));

/**
 * Returns currency info by ISO code or default USD
 */
export function getCurrencyInfo(code?: string): CurrencyInfo {
  if (!code) return CURRENCY_MAP.get('USD')!;
  return CURRENCY_MAP.get(code.toUpperCase()) || {
    code: code.toUpperCase(),
    symbol: code.toUpperCase(),
    name: code.toUpperCase(),
    country: 'Custom'
  };
}

/**
 * Gets currency symbol for given code, e.g. 'USD' -> '$', 'EUR' -> '€', 'PKR' -> 'Rs'
 */
export function getCurrencySymbol(code?: string): string {
  return getCurrencyInfo(code).symbol;
}
